services:
  n8n-editor:
    image: n8nio/n8n:1.114.3
    container_name: n8n-editor-pmmp
    ports:
      - 5678:5678
    volumes:
      - ./n8n-data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      ## Postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres
      ## Queue Mode
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
    networks:
      - n8n-automacoes
    depends_on:
      - postgres
      - redis
    restart: always


  n8n-worker:
    image: n8nio/n8n:1.114.3
    command: worker
    ports:
      - 5679:5678
    volumes:
      - ./n8n-data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      ## Postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres
      ## Queue Mode
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
    networks:
      - n8n-automacoes
    depends_on:
      - postgres
      - redis
    restart: always


  postgres:
    image: ankane/pgvector
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    networks:
      - n8n-automacoes
    restart: always


  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    networks:
      - n8n-automacoes
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - 4040:4040
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command: http --domain=vibrationless-ashley-proconscription.ngrok-free.dev n8n-editor-pmmp:5678
    environment:
      - NGROK_AUTHTOKEN=39DPGxIkrbEtrIhspqCrUkWLZfs_6PTn2M29mfgQXp3KuDrdM
    restart: always
    networks:
      - n8n-automacoes
    depends_on:
      - n8n-editor

networks:
  n8n-automacoes:
    driver: bridge